language: php
dist: precise
sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - COVERAGE=0
    - PHPCS=0
    - PHPMD=0
    - PHPSTAN=0
    - PHPUNIT=1
    - REMOVE_XDEBUG=1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: COVERAGE=1 PHPCS=1 PHPMD=1 PHPSTAN=1 REMOVE_XDEBUG=0
    - php: nightly
      env: REMOVE_XDEBUG=0
  allow_failures:
    - php: nightly

before_script:
  - if [[ $REMOVE_XDEBUG == 1 ]]; then phpenv config-rm xdebug.ini; fi
  - if [[ $COVERAGE == 1 ]]; then composer require-coverage; fi
  - if [[ $PHPCS == 1 ]]; then composer require-phpcs; fi
  - if [[ $PHPMD == 1 ]]; then composer require-phpmd; fi
  - if [[ $PHPSTAN == 1 ]]; then composer require-phpstan; fi
  - composer update -o --prefer-dist --no-interaction

script:
  - if [[ $PHPSTAN == 1 ]]; then composer test-phpstan; fi
  - if [[ $PHPMD == 1 ]]; then composer test-phpmd; fi
  - if [[ $PHPUNIT == 1 ]] && [[ $COVERAGE != 1 ]]; then composer test-phpunit; fi
  - if [[ $PHPUNIT == 1 ]] && [[ $COVERAGE == 1 ]]; then composer test-phpunit-coverage; fi

after_success:
  - if [[ $PHPUNIT == 1 ]] && [[ $COVERAGE == 1 ]]; then composer upload-coverage; fi

notifications:
  email:
    on_success: never
    on_failure: always
